blueprint:
  name: Sensibo Aircon Toggle
  description: >
    Toggle a Sensibo AC by selecting device and action.
    "on" = cool mode + temperature,
    "off" = fan mode, delay, then turn off.
  domain: script

  input:
    sensibo_device:
      name: Sensibo Device
      description: Select your Sensibo climate entity
      selector:
        entity:
          domain: climate

    operation:
      name: Operation
      description: Choose to turn on or turn off the AC
      default: "on"
      selector:
        select:
          options:
            - label: "Turn On"
              value: "on"
            - label: "Turn Off"
              value: "off"

    target_temp:
      name: Target Temperature
      description: Temperature to set when turning on (°C)
      default: 25
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: °C

    off_delay:
      name: Turn Off Delay (min)
      description: Delay before turning off after switching to fan mode (minutes)
      default: 30
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: min

mode: single

sequence:
  # Define variables at the sequence level to make them accessible throughout
  - variables:
      current_operation: !input operation
      current_sensibo_device: !input sensibo_device
      current_target_temp: !input target_temp

  - service: system_log.write
    data:
      level: info
      message: >
        [Sensibo AC] Operation value: {{ current_operation }}. Device: {{ current_sensibo_device }}. Target Temp: {{ current_target_temp }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ current_operation == 'on' }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input sensibo_device
            data:
              hvac_mode: cool
          - delay:
              seconds: 5
          - service: climate.set_temperature
            target:
              entity_id: !input sensibo_device
            data:
              temperature: "{{ current_target_temp }}"
          - service: climate.set_fan_mode
            target:
              entity_id: !input sensibo_device
            data:
              fan_mode: auto

      - conditions:
          - condition: template
            value_template: "{{ current_operation == 'off' }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input sensibo_device
            data:
              hvac_mode: fan_only
          - service: climate.set_fan_mode
            target:
              entity_id: !input sensibo_device
            data:
              fan_mode: auto
          - delay:
              minutes: !input off_delay
          - service: climate.turn_off
            target:
              entity_id: !input sensibo_device
